# Juntando R y Python

In [1]:
import pandas as pd
import numpy as np

In [2]:
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
import rpy2.robjects as ro
import rpy2.robjects.numpy2ri

In [4]:
rpy2.robjects.numpy2ri.activate()

In [5]:
codigo_r = """
    saludar <- function(cadena) {
        return(paste("Hola, ", cadena))
    }
"""

In [6]:
ro.r(codigo_r)

R object with classes: ('function',) mapped to:
<SignatureTranslatedFunction - Python:0x1186cad88 / R:0x7f87142eff90>

In [7]:
saludar_py = ro.globalenv["saludar"]

In [8]:
res = saludar_py("Diego")
res[0]

'Hola,  Diego'

In [9]:
type(res)

rpy2.robjects.vectors.StrVector

In [10]:
print(saludar_py.r_repr())

function (cadena) 
{
    return(paste("Hola, ", cadena))
}


In [11]:
var_from_python = ro.FloatVector(np.arange(1,5,0.1))

In [12]:
var_from_python

R object with classes: ('numeric',) mapped to:
<FloatVector - Python:0x1257b4ac8 / R:0x7f8713a785b0>
[1.000000, 1.100000, 1.200000, 1.300000, ..., 4.600000, 4.700000, 4.800000, 4.900000]

In [13]:
print(var_from_python.r_repr())

c(1, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2, 2.1, 2.2, 
2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3, 3.1, 3.2, 3.3, 3.4, 3.5, 
3.6, 3.7, 3.8, 3.9, 4, 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 
4.9)


In [14]:
ro.globalenv["var_to_r"] = var_from_python

In [15]:
ro.r("var_to_r")

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9])

In [16]:
ro.r("mean(var_to_r)")

array([2.95])

In [17]:
ro.r("sd(var_to_r)")

array([1.16904519])

In [18]:
np.sum(var_from_python)

118.00000000000007

In [19]:
np.mean(var_from_python)

2.950000000000002

In [20]:
ro.r("summary(var_to_r)") 

array([1.   , 1.975, 2.95 , 2.95 , 3.925, 4.9  ])

Mínimo, primer cuartil, mediana, media, tercer cuartil, máximo

In [22]:
ro.r("hist(var_to_r)")

R object with classes: ('histogram',) mapped to:
<ListVector - Python:0x12f9c2708 / R:0x7f93af939578>
[Float..., IntVe..., Float..., Float..., StrVe..., BoolV...]
  breaks: <class 'rpy2.robjects.vectors.FloatVector'>
  R object with classes: ('numeric',) mapped to:
<FloatVector - Python:0x12f9c2488 / R:0x7f93b573dcc8>
[1.000000, 1.500000, 2.000000, 2.500000, ..., 3.500000, 4.000000, 4.500000, 5.000000]
  counts: <class 'rpy2.robjects.vectors.IntVector'>
  R object with classes: ('integer',) mapped to:
<IntVector - Python:0x12f9c2448 / R:0x7f93b04b0e88>
[6, 5, 5, 5, 5, 5, 5, 4]
  density: <class 'rpy2.robjects.vectors.FloatVector'>
  R object with classes: ('numeric',) mapped to:
<FloatVector - Python:0x12f9c22c8 / R:0x7f93af9384d8>
[0.300000, 0.250000, 0.250000, 0.250000, 0.250000, 0.250000, 0.250000, 0.200000]
  mids: <class 'rpy2.robjects.vectors.FloatVector'>
  R object with classes: ('numeric',) mapped to:
<FloatVector - Python:0x12f9c2508 / R:0x7f93af938e78>
[1.250000, 1.750000, 2.250000, 2.750000, 3.250000, 3.750000, 4.250000, 4.750000]
  xname: <class 'rpy2.robjects.vectors.StrVector'>
  R object with classes: ('character',) mapped to:
<StrVector - Python:0x12f9c2308 / R:0x7f93b61242b0>
['var_to_r']
  equidist: <class 'rpy2.robjects.vectors.BoolVector'>
  R object with classes: ('logical',) mapped to:
<BoolVector - Python:0x12f9c20c8 / R:0x7f93b017fce0>
[       1]

# Trabajar de forma conjunta entre R y Python

In [5]:
from rpy2.robjects.packages import importr

In [6]:
ro.r("install.packages('extRemes')")

--- Please select a CRAN mirror for use in this session ---



Secure CRAN mirrors
 





 1: 0-Cloud [https]                   2: Algeria [https]                
 3: Australia (Canberra) [https]      4: Australia (Melbourne 1) [https]
 5: Australia (Melbourne 2) [https]   6: Australia (Perth) [https]      
 7: Austria [https]                   8: Belgium (Ghent) [https]        
 9: Brazil (PR) [https]              10: Brazil (RJ) [https]            
11: Brazil (SP 1) [https]            12: Brazil (SP 2) [https]          
13: Bulgaria [https]                 14: Chile 1 [https]                
15: Chile 2 [https]                  16: China (Hong Kong) [https]      
17: China (Guangzhou) [https]        18: China (Lanzhou) [https]        
19: China (Shanghai 1) [https]       20: China (Shanghai 2) [https]     
21: Colombia (Cali) [https]          22: Czech Republic [https]         
23: Denmark [https]                  24: East Asia [https]              
25: Ecuador (Cuenca) [https]      

/anaconda3/lib/python3.7/site-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: also installing the dependencies ‘readr’, ‘zip’, ‘Matrix’, ‘SparseM’, ‘MatrixModels’, ‘sp’, ‘foreign’, ‘lattice’, ‘haven’, ‘curl’, ‘data.table’, ‘readxl’, ‘openxlsx’, ‘minqa’, ‘nloptr’, ‘RcppEigen’, ‘MASS’, ‘mgcv’, ‘nnet’, ‘pbkrtest’, ‘quantreg’, ‘maptools’, ‘rio’, ‘lme4’, ‘nlme’, ‘car’


  warnings.warn(x, RRuntimeWarning)
/anaconda3/lib/python3.7/site-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: probando la URL 'https://cran.rediris.es/src/contrib/readr_1.3.1.tar.gz'

  warnings.warn(x, RRuntimeWarning)
/anaconda3/lib/python3.7/site-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: Content type 'application/x-gzip'
  warnings.warn(x, RRuntimeWarning)
/anaconda3/lib/python3.7/site-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning:  length 268853 bytes (262 KB)

  warnings.warn(x, RRuntimeWarning)
/anaconda3/lib/python3.7/site-packages/rpy2/rinterface/__init__.py:146:

/anaconda3/lib/python3.7/site-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning:  length 1633859 bytes (1.6 MB)

  warnings.warn(x, RRuntimeWarning)
/anaconda3/lib/python3.7/site-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: downloaded 1.6 MB


  warnings.warn(x, RRuntimeWarning)
/anaconda3/lib/python3.7/site-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: probando la URL 'https://cran.rediris.es/src/contrib/MASS_7.3-51.1.tar.gz'

  warnings.warn(x, RRuntimeWarning)
/anaconda3/lib/python3.7/site-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning:  length 487241 bytes (475 KB)

  warnings.warn(x, RRuntimeWarning)
/anaconda3/lib/python3.7/site-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: downloaded 475 KB


  warnings.warn(x, RRuntimeWarning)
/anaconda3/lib/python3.7/site-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: probando la URL 'https://cran.rediris.es/src/contrib/mgcv_1.8-27.tar.gz'

  warnings.warn(x, RRuntimeWarnin

rpy2.rinterface.NULL

In [7]:
extremes = importr("extRemes") # library(extRemes)

/anaconda3/lib/python3.7/site-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: Error in loadNamespace(name) : there is no package called ‘extRemes’

  warnings.warn(x, RRuntimeWarning)
/anaconda3/lib/python3.7/site-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: Además: 
  warnings.warn(x, RRuntimeWarning)
/anaconda3/lib/python3.7/site-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: There were 27 warnings (use warnings() to see them)
  warnings.warn(x, RRuntimeWarning)
/anaconda3/lib/python3.7/site-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: 

  warnings.warn(x, RRuntimeWarning)


RRuntimeError: Error in loadNamespace(name) : there is no package called ‘extRemes’


# Función mágica para R

In [8]:
%load_ext rpy2.ipython

ModuleNotFoundError: No module named 'tzlocal'