# El método de k-means

In [3]:
import numpy as np
import pandas as pd

In [5]:
data = np.random.random(90).reshape(30,3) #30 filas y 3 columnas
data

array([[0.07236174, 0.949764  , 0.15393883],
       [0.97283662, 0.2847066 , 0.34920495],
       [0.54608246, 0.30382516, 0.6948351 ],
       [0.93359073, 0.07372862, 0.92095259],
       [0.94930575, 0.79213933, 0.66084221],
       [0.89313985, 0.44915995, 0.89686356],
       [0.22153177, 0.96495664, 0.17707337],
       [0.76604699, 0.90859502, 0.50623775],
       [0.05808873, 0.71741686, 0.26974925],
       [0.15368309, 0.05042747, 0.11854935],
       [0.09823746, 0.62846257, 0.03494873],
       [0.71585988, 0.56882682, 0.2419654 ],
       [0.77472337, 0.50745239, 0.11654146],
       [0.18597824, 0.51557088, 0.15855749],
       [0.13031282, 0.79999747, 0.14057391],
       [0.36627076, 0.59676753, 0.00365955],
       [0.13858909, 0.73226246, 0.93871698],
       [0.28235475, 0.44081791, 0.44710555],
       [0.67801838, 0.30937444, 0.79740528],
       [0.42000377, 0.1057822 , 0.97734697],
       [0.48412629, 0.93736889, 0.8933974 ],
       [0.20704104, 0.25498347, 0.28848301],
       [0.

In [6]:
#Elijo dos elementos al azar entre los que componen data como centroide de los clusters
c1 = np.random.choice(range(len(data)))
c2 = np.random.choice(range(len(data)))
clust_centers = np.vstack([data[c1],data[c2]])
clust_centers

array([[0.54608246, 0.30382516, 0.6948351 ],
       [0.38754136, 0.7665612 , 0.58354986]])

In [7]:
from scipy.cluster.vq import vq

In [8]:
vq(data, clust_centers)

(array([1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
        1, 1, 0, 0, 0, 1, 0, 1], dtype=int32),
 array([0.56344218, 0.54949507, 0.        , 0.50421841, 0.56763332,
        0.42706736, 0.48181228, 0.4116033 , 0.45762979, 0.74181732,
        0.63539844, 0.51339252, 0.65434261, 0.53314383, 0.51333439,
        0.60461152, 0.43508312, 0.3684969 , 0.16720802, 0.36732793,
        0.36675525, 0.53146648, 0.4346588 , 0.12040561, 0.41204934,
        0.49937329, 0.09541779, 0.15689776, 0.43964568, 0.        ]))

In [9]:
from scipy.cluster.vq import kmeans

In [11]:
kmeans(data, clust_centers) #Nos da la información de los baricentros

(array([[0.56414434, 0.21654647, 0.62716719],
        [0.40451021, 0.71932415, 0.40849161]]), 0.40899986360517826)